# Generated by Django 4.2.4 on 2023-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
