# Generated by Django 4.2.4 on 2023-08-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userclass_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='SecondName',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='password',
        ),
    ]
