# Generated by Django 4.1.10 on 2023-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveau', '0001_initial'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveau.niveau'),
        ),
    ]
