# Generated by Django 4.2.4 on 2023-08-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('chapitre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='chapitres_suivis', to='user.userclass'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userclass'),
        ),
        migrations.AddField(
            model_name='score',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userclass'),
            preserve_default=False,
        ),
    ]
