# Generated by Django 4.1.10 on 2023-08-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0002_chapitre_student_chapitre_teacher_score_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='score',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='student',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='teacher',
        ),
    ]
