# Generated by Django 4.1.10 on 2023-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
        ('chapitre', '0003_remove_score_chapitre_remove_score_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
